# Module manifest for module 'Gioxx.ToyBox'
# Generated by: Gioxx
# Generated on: 01/07/2022

@{
  RootModule = '.\Gioxx.ToyBox.psm1'
  ModuleVersion = '0.2'

  # Supported PSEditions
  # CompatiblePSEditions = @()

  GUID = '17aadfab-2909-411f-9266-29177b510755'
  Author = 'Gioxx'
  CompanyName = 'Gioxx.org'
  Copyright = '(c)opyleft, since the dawn of time, Gioxx.org'

  # Description of the functionality provided by this module
  # Description = ''

  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '7.0'

  # Name of the PowerShell host required by this module
  # PowerShellHostName = ''

  # Minimum version of the PowerShell host required by this module
  # PowerShellHostVersion = ''

  # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # DotNetFrameworkVersion = ''

  # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
  # ClrVersion = ''

  # Processor architecture (None, X86, Amd64) required by this module
  # ProcessorArchitecture = ''

  # Modules that must be imported into the global environment prior to importing this module
  # RequiredModules = @()

  # Assemblies that must be loaded prior to importing this module
  # RequiredAssemblies = @()

  # Script files (.ps1) that are run in the caller's environment prior to importing this module.
  # ScriptsToProcess = @()

  # Type files (.ps1xml) to be loaded when importing this module
  # TypesToProcess = @()

  # Format files (.ps1xml) to be loaded when importing this module
  # FormatsToProcess = @()

  # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
  # NestedModules = @()

  FunctionsToExport = @(
    "AddMboxPermission",
    "MboxPermission",
    "QuarantineRelease",
    "RemoveMboxPermission"
  )
  CmdletsToExport = @(
    "AddMboxPermission",
    "MboxPermission",
    "QuarantineRelease",
    "RemoveMboxPermission"
  )
  VariablesToExport = '*' # Variables to export from this module
  AliasesToExport = @() # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.

  # DSC resources to export from this module
  # DscResourcesToExport = @()

  # List of all modules packaged with this module
  #ModuleList = @()

  # List of all files packaged with this module
  #FileList = @()

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData = @{
    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      # Tags = @()

      # A URL to the license for this module.
      # LicenseUri = ''

      # A URL to the main website for this project.
      # ProjectUri = ''

      # A URL to an icon representing this module.
      # IconUri = ''

      # ReleaseNotes of this module
      # ReleaseNotes = ''

      Prerelease = 'Preview1'

      # Flag to indicate whether the module requires explicit user acceptance for install/update/save
      # RequireLicenseAcceptance = $false

      # External dependent modules of this module
      # ExternalModuleDependencies = @()

      } # End of PSData hashtable

  } # End of PrivateData hashtable

  # HelpInfo URI of this module
  # HelpInfoURI = ''

  # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
  # DefaultCommandPrefix = ''

}
